version: '3.8'

services:
  dev-db:
    image: postgres:15
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb

  test-db:
    image: postgres:15
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
